"""Regenerate every app icon from assets/branding/mchart_mark_master.png.

Run from the app/ directory:  python tool/generate_icons.py
"""
from PIL import Image
import os

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
MASTER = os.path.join(ROOT, "assets", "branding", "mchart_mark_master.png")

master = Image.open(MASTER).convert("RGBA")


def save(size, path, mode="RGBA"):
    im = master.resize((size, size), Image.LANCZOS)
    if mode == "RGB":
        bg = Image.new("RGB", (size, size), (255, 255, 255))
        bg.paste(im, mask=im.split()[3])
        im = bg
    os.makedirs(os.path.dirname(path), exist_ok=True)
    im.save(path)
    print("wrote", path, im.size, im.mode)


# ---- Web (PWA) ----
save(16, os.path.join(ROOT, "web", "favicon.png"))
save(192, os.path.join(ROOT, "web", "icons", "Icon-192.png"), "RGB")
save(512, os.path.join(ROOT, "web", "icons", "Icon-512.png"), "RGB")
save(192, os.path.join(ROOT, "web", "icons", "Icon-maskable-192.png"))
save(512, os.path.join(ROOT, "web", "icons", "Icon-maskable-512.png"))

# ---- Android launcher (legacy square mipmaps) ----
android = {
    "mipmap-mdpi": 48,
    "mipmap-hdpi": 72,
    "mipmap-xhdpi": 96,
    "mipmap-xxhdpi": 144,
    "mipmap-xxxhdpi": 192,
}
for folder, size in android.items():
    save(size, os.path.join(ROOT, "android", "app", "src", "main", "res", folder, "ic_launcher.png"))

# ---- Windows (multi-size .ico) ----
ico_path = os.path.join(ROOT, "windows", "runner", "resources", "app_icon.ico")
os.makedirs(os.path.dirname(ico_path), exist_ok=True)
ico_sizes = [16, 24, 32, 48, 64, 128, 256]
master.resize((256, 256), Image.LANCZOS).save(
    ico_path, sizes=[(s, s) for s in ico_sizes]
)
print("wrote", ico_path, ico_sizes)

print("Done. macOS .icns and Android adaptive-icon layers are not generated by this script.")
